// polaris-web/app/components/ui/EmptyState.vue
<template>
  <div class="flex flex-col items-center justify-center gap-4 py-16">
    <div class="flex size-12 items-center justify-center rounded-lg border border-white/10 bg-white/8">
      <slot name="icon" />
    </div>
    <h2 class="text-lg font-medium text-white">{{ title }}</h2>
    <p class="text-sm text-white/55">{{ body }}</p>
    <slot />
  </div>
</template>

<script setup lang="ts">
defineProps<{
  title?: string
  body?: string
}>()
</script>

// components/ui/EmptyState.tsx
import { Sparkles } from "lucide-react";

export function EmptyState({ title, body }: { title: string; body: string }) {
  return (
    <div className="pointer-events-none absolute inset-0 grid place-items-center">
      <div className="max-w-md text-center">
        <div className="mx-auto mb-4 grid size-12 place-items-center rounded-lg border border-white/10 bg-white/8">
          <Sparkles className="size-5 text-studio-cyan" />
        </div>
        <h2 className="text-lg font-medium text-white">{title}</h2>
        <p className="mt-2 text-sm leading-6 text-white/55">{body}</p>
      </div>
    </div>
  );
}
