// components/canvas/CanvasCard.tsx
"use client";

import { Copy, Grip, Trash2, Workflow } from "lucide-react";
import { useRef } from "react";
import { ImageCard } from "@/components/canvas/ImageCard";
import { PromptCard } from "@/components/canvas/PromptCard";
import { VideoCard } from "@/components/canvas/VideoCard";
import { useCanvasStore } from "@/stores/useCanvasStore";
import { useWorkspaceStore } from "@/stores/useWorkspaceStore";
import type { CanvasObject } from "@/types";
import { cn } from "@/lib/utils";

export function CanvasCard({ object }: { object: CanvasObject }) {
  const selectedId = useCanvasStore((state) => state.selectedId);
  const selectObject = useCanvasStore((state) => state.selectObject);
  const updateObject = useCanvasStore((state) => state.updateObject);
  const duplicateObject = useCanvasStore((state) => state.duplicateObject);
  const deleteSelected = useCanvasStore((state) => state.deleteSelected);
  const setMode = useWorkspaceStore((state) => state.setMode);
  const start = useRef({ x: 0, y: 0, ox: 0, oy: 0 });
  const selected = selectedId === object.id;

  return (
    <div
      onPointerDown={(event) => {
        selectObject(object.id);
        start.current = { x: event.clientX, y: event.clientY, ox: object.x, oy: object.y };
        (event.currentTarget as HTMLDivElement).setPointerCapture(event.pointerId);
      }}
      onPointerMove={(event) => {
        if (!(event.buttons & 1)) return;
        updateObject(object.id, {
          x: start.current.ox + event.clientX - start.current.x,
          y: start.current.oy + event.clientY - start.current.y
        });
      }}
      className={cn(
        "glass group absolute rounded-lg p-3 transition hover:border-cyan-300/30",
        selected ? "border-cyan-300/45 shadow-glow" : "border-white/10"
      )}
      style={{ left: object.x, top: object.y, width: object.width, minHeight: object.height }}
    >
      <div className="mb-3 flex items-center justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2">
          <Grip className="size-4 shrink-0 text-white/28" />
          <span className="truncate text-sm font-medium text-white/86">{object.title}</span>
        </div>
        <div className="flex opacity-0 transition group-hover:opacity-100">
          <button title="复制 / Duplicate" onClick={(event) => { event.stopPropagation(); duplicateObject(object.id); }} className="grid size-7 place-items-center rounded hover:bg-white/10">
            <Copy className="size-3.5" />
          </button>
          <button title="发送到工作流 / Send to workflow" onClick={(event) => { event.stopPropagation(); setMode("workflow-nodes"); }} className="grid size-7 place-items-center rounded hover:bg-white/10">
            <Workflow className="size-3.5" />
          </button>
          <button title="删除 / Delete" onClick={(event) => { event.stopPropagation(); deleteSelected(); }} className="grid size-7 place-items-center rounded hover:bg-white/10">
            <Trash2 className="size-3.5" />
          </button>
        </div>
      </div>
      {object.type === "prompt" ? <PromptCard content={object.content} /> : null}
      {object.type === "image" || object.type === "generated" || object.type === "moodboard" || object.type === "reference" ? <ImageCard content={object.content} /> : null}
      {object.type === "video" ? <VideoCard content={object.content} /> : null}
      {object.type === "text" || object.type === "audio" ? <p className="text-sm leading-6 text-white/62">{object.content}</p> : null}
    </div>
  );
}

// polaris-web/app/components/canvas/CanvasCard.vue
<template>
  <div
    class="glass group absolute rounded-lg border p-3 transition hover:border-cyan-300/30"
    :class="selected ? 'border-cyan-300/45 shadow-glow' : 'border-white/10'"
    :style="{ left: object.x + 'px', top: object.y + 'px', width: object.width + 'px', minHeight: object.height + 'px' }"
    @click.stop="$emit('select')"
  >
    <div class="mb-3 flex items-center justify-between gap-3">
      <div class="flex min-w-0 flex-1 items-center gap-2">
        <button class="grid size-7 shrink-0 cursor-grab place-items-center rounded text-white/35 hover:bg-white/8 hover:text-white/70" @mousedown.stop.prevent="startDrag">
          <GripVertical class="size-4" />
        </button>
        <input
          :value="object.title"
          class="min-w-0 flex-1 truncate rounded border border-transparent bg-transparent px-1 py-1 text-sm font-medium text-white/86 outline-none focus:border-cyan-300/30 focus:bg-black/20"
          @input="updateTitle"
          @mousedown.stop
          @click.stop
        />
      </div>
      <div class="flex opacity-0 transition group-hover:opacity-100" :class="{ 'opacity-100': selected }">
        <button title="Duplicate" class="grid size-7 place-items-center rounded hover:bg-white/10" @click.stop="$emit('duplicate')">
          <Copy class="size-3.5" />
        </button>
        <button title="Send to workflow" class="grid size-7 place-items-center rounded hover:bg-white/10" @click.stop="$emit('sendToWorkflow')">
          <Workflow class="size-3.5" />
        </button>
        <button title="Delete" class="grid size-7 place-items-center rounded hover:bg-white/10 hover:text-red-300" @click.stop="$emit('delete')">
          <Trash2 class="size-3.5" />
        </button>
      </div>
    </div>

    <PromptCard v-if="object.type === 'prompt'" :content="object.content" @update="updateContent" />
    <ImageCard v-else-if="['image', 'generated', 'moodboard', 'reference'].includes(object.type)" :content="object.content" @update="updateContent" />
    <VideoCard v-else-if="object.type === 'video'" :content="object.content" @update="updateContent" />
    <textarea
      v-else
      :value="object.content"
      class="min-h-28 w-full resize-none rounded-lg border border-white/8 bg-black/20 p-3 text-sm leading-6 text-white/72 outline-none focus:border-cyan-300/30"
      @input="updateContent"
      @mousedown.stop
      @click.stop
    />

    <div
      class="absolute bottom-1 right-1 size-4 cursor-nwse-resize rounded-sm border-b border-r border-cyan-100/35 opacity-0 transition group-hover:opacity-100"
      @mousedown.stop.prevent="startResize"
    />
  </div>
</template>

<script setup lang="ts">
import { Copy, GripVertical, Trash2, Workflow } from 'lucide-vue-next'
import PromptCard from '~/components/canvas/PromptCard.vue'
import ImageCard from '~/components/canvas/ImageCard.vue'
import VideoCard from '~/components/canvas/VideoCard.vue'
import type { CanvasObject } from '~/types'

const props = defineProps<{
  object: CanvasObject
  selected?: boolean
}>()

const emit = defineEmits<{
  select: []
  delete: []
  duplicate: []
  move: [x: number, y: number]
  resize: [width: number, height: number]
  update: [data: Partial<CanvasObject>]
  sendToWorkflow: []
}>()

function updateTitle(event: Event) {
  emit('update', { title: (event.target as HTMLInputElement).value })
}

function updateContent(valueOrEvent: string | Event) {
  const content = typeof valueOrEvent === 'string'
    ? valueOrEvent
    : (valueOrEvent.target as HTMLTextAreaElement).value
  emit('update', { content })
}

function startDrag(event: MouseEvent) {
  emit('select')
  const startX = event.clientX
  const startY = event.clientY
  const objX = props.object.x
  const objY = props.object.y

  function onMove(ev: MouseEvent) {
    emit('move', objX + ev.clientX - startX, objY + ev.clientY - startY)
  }

  function onUp() {
    document.removeEventListener('mousemove', onMove)
    document.removeEventListener('mouseup', onUp)
  }

  document.addEventListener('mousemove', onMove)
  document.addEventListener('mouseup', onUp)
}

function startResize(event: MouseEvent) {
  emit('select')
  const startX = event.clientX
  const startY = event.clientY
  const startW = props.object.width
  const startH = props.object.height

  function onMove(ev: MouseEvent) {
    emit('resize', startW + ev.clientX - startX, startH + ev.clientY - startY)
  }

  function onUp() {
    document.removeEventListener('mousemove', onMove)
    document.removeEventListener('mouseup', onUp)
  }

  document.addEventListener('mousemove', onMove)
  document.addEventListener('mouseup', onUp)
}
</script>
