// polaris-web/app/components/workflow/NodeMenu.vue
<template>
  <div class="rounded-lg border border-white/10 bg-[#11131a]/95 p-2 shadow-glass backdrop-blur-xl">
    <button
      v-for="node in nodeTypes"
      :key="node.key"
      class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-white/68 transition hover:bg-white/8 hover:text-cyan-50"
      @click="$emit('select', node.key)"
    >
      <component :is="node.icon" class="size-4" />
      {{ node.label }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { FileText, Image, Video, Sparkles, Merge, ExternalLink } from 'lucide-vue-next'

defineEmits<{
  select: [type: string]
}>()

const nodeTypes = [
  { key: 'prompt', icon: FileText, label: 'Prompt' },
  { key: 'image-gen', icon: Image, label: 'Image Generation' },
  { key: 'video-gen', icon: Video, label: 'Video Generation' },
  { key: 'enhance', icon: Sparkles, label: 'Enhance' },
  { key: 'merge', icon: Merge, label: 'Merge' },
  { key: 'output', icon: ExternalLink, label: 'Output' }
]
</script>

// components/workflow/NodeMenu.tsx
"use client";

import type { WorkflowNodeType } from "@/types";

const groups: { title: string; items: { label: string; type: WorkflowNodeType }[] }[] = [
  { title: "输入 / Input", items: [{ label: "文本 / Text", type: "text" }, { label: "提示词 / Prompt", type: "prompt" }, { label: "图像 / Image", type: "image" }, { label: "视频 / Video", type: "video" }] },
  { title: "生成 / Generate", items: [{ label: "文生图 / Text to Image", type: "image-generate" }, { label: "图生视频 / Image to Video", type: "image-to-video" }] },
  { title: "输出 / Output", items: [{ label: "导出 / Export", type: "output" }] }
];

export function NodeMenu({ onAdd }: { onAdd: (type: WorkflowNodeType) => void }) {
  return (
    <div className="absolute left-5 top-5 z-20 w-56 rounded-lg border border-white/10 bg-black/60 p-3 shadow-glass backdrop-blur-xl">
      {groups.map((group) => (
        <div key={group.title} className="mb-3 last:mb-0">
          <div className="mb-2 text-[11px] uppercase tracking-wider text-white/35">{group.title}</div>
          <div className="grid gap-1">
            {group.items.map((item) => (
              <button
                key={item.type}
                onClick={() => onAdd(item.type)}
                className="rounded-md px-2 py-1.5 text-left text-xs text-white/68 transition hover:bg-white/10 hover:text-white"
              >
                {item.label}
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
